// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDZKfQ5ktdiJHwp5K049UOopcmYYrdso',
    appId: '1:393639006879:web:80d49d7e47744bb52e88aa',
    messagingSenderId: '393639006879',
    projectId: 'app-telemedicine-run',
    authDomain: 'app-telemedicine-run.firebaseapp.com',
    databaseURL: 'https://app-telemedicine-run-default-rtdb.firebaseio.com',
    storageBucket: 'app-telemedicine-run.appspot.com',
    measurementId: 'G-NT7XFV5E2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnMUZrhrVuKuRGCGEgsFz_iFIdDvhUbRw',
    appId: '1:393639006879:android:dfc7881fbc6629f62e88aa',
    messagingSenderId: '393639006879',
    projectId: 'app-telemedicine-run',
    databaseURL: 'https://app-telemedicine-run-default-rtdb.firebaseio.com',
    storageBucket: 'app-telemedicine-run.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP06qkHvMaxRoBc_PySXrDA--vYMna2eU',
    appId: '1:393639006879:ios:49a4efcb28a859a22e88aa',
    messagingSenderId: '393639006879',
    projectId: 'app-telemedicine-run',
    databaseURL: 'https://app-telemedicine-run-default-rtdb.firebaseio.com',
    storageBucket: 'app-telemedicine-run.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP06qkHvMaxRoBc_PySXrDA--vYMna2eU',
    appId: '1:393639006879:ios:7aa5f8f2381f5a3a2e88aa',
    messagingSenderId: '393639006879',
    projectId: 'app-telemedicine-run',
    databaseURL: 'https://app-telemedicine-run-default-rtdb.firebaseio.com',
    storageBucket: 'app-telemedicine-run.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
